name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sanity_tests:
    name: Sanity Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - shardNumber: '1'
          - shardNumber: '2'
    outputs:
      shard1: ${{ steps.shard1.outputs }}
    steps:
      - name: Run Acceptance Tests
        id: shard1
        run: |
          echo "::set-output name=ephemeralNamespace::$EPHEMERAL_NAMESPACE"
          echo "::set-output name=shardNumber::$SHARD_NUMBER"
          echo "::set-output name=tag::$TAG"
        env:
          SHARD_NUMBER: ${{ matrix.shardNumber }}
          TAG: "@sanity"
  print_results:
    name: Print Results
    runs-on: ubuntu-latest
    needs: sanity_tests
    steps:
      - run: |
          echo ${{ needs.sanity_tests.outputs.shard1 }}