name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [a, b, c]

    outputs:
      deploy-url-a: ${{ steps.deploy-url.outputs.a }}
      deploy-url-b: ${{ steps.deploy-url.outputs.b }}
      deploy-url-c: ${{ steps.deploy-url.outputs.c }}

    steps:
      - id: deploy
        run: echo '::set-output name=details_url::http://${{ matrix.app }}'

      - id: deploy-url
        run: echo '::set-output name=${{ matrix.app }}::${{ steps.deploy.outputs.details_url }}'

  e2e:
    runs-on: ubuntu-latest
    needs:
      - build

    strategy:
      matrix:
        container: [A, B, C, D, E, F]

    steps:
      - env:
          NEEDS: ${{ toJSON(needs) }}
        run: echo "$NEEDS"